
const GITHUB_AUTH_TOKEN = ""
const GITHUB_USERNAME = "Dilip-ma"
const SESSION_ID = "𝙰𝚂𝙸𝚃𝙷𝙰-𝙼𝙳=Du5UxBYD#cIfSr3OK8AVw-XukGB7ArnNYiS1_5FFPjK7Ao749-zE"


module.exports = {
GITHUB_AUTH_TOKEN,
GITHUB_USERNAME,
SESSION_ID
}
